@messageId = cebb207b-56ff-415e-a4ba-636ceab86530
@yourToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODMxNywiZW1haWwiOiJqYWNrQGV4cGxvcmF0b3IuY2EiLCJ1c2VybmFtZSI6ImphY2tAZXhwbG9yYXRvci5jYSIsImlhdCI6MTcwNTUwNzg1Mn0.E39vgmRb92oKUf0CZi1AKnRPjkMMZ5VQG92pklpiMQg


### 

GET https://api.mymidjourney.ai/api/v1/midjourney/message/{{messageId}}
Authorization: Bearer {{yourToken}}



### 

@id = 274
https://api.mymidjourney.ai/api/v1/discord/queue/{{id}}
Authorization: Bearer {{yourToken}}




### 

GET https://api.mymidjourney.ai/api/v1/discord/tokens
Authorization: Bearer {{yourToken}}