create table "public"."student_message_submissions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "temporary_account_profile_id" bigint not null,
    "message_content" text not null default ''::text,
    "image_file_url" text not null default ''::text
);


alter table "public"."student_message_submissions" enable row level security;

CREATE UNIQUE INDEX student_message_submissions_pkey ON public.student_message_submissions USING btree (id);

alter table "public"."student_message_submissions" add constraint "student_message_submissions_pkey" PRIMARY KEY using index "student_message_submissions_pkey";

alter table "public"."student_message_submissions" add constraint "student_message_submissions_temporary_account_profile_id_fkey" FOREIGN KEY (temporary_account_profile_id) REFERENCES temporary_account_profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."student_message_submissions" validate constraint "student_message_submissions_temporary_account_profile_id_fkey";

create policy "Enable read for authenticated users only"
on "public"."student_message_submissions"
as permissive
for select
to authenticated
using (true);



