create table "public"."teacher_settings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "teacher_profile_id" uuid not null,
    "allow_student_use_line" boolean not null default false
);


alter table "public"."teacher_settings" enable row level security;

CREATE UNIQUE INDEX teacher_settings_pkey ON public.teacher_settings USING btree (id);

alter table "public"."teacher_settings" add constraint "teacher_settings_pkey" PRIMARY KEY using index "teacher_settings_pkey";

alter table "public"."teacher_settings" add constraint "teacher_settings_teacher_profile_id_fkey" FOREIGN KEY (teacher_profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."teacher_settings" validate constraint "teacher_settings_teacher_profile_id_fkey";


