create table "public"."temporary_account_profiles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "uniqueId" text not null default ''::text,
    "profile_id" uuid,
    "one_time_code_id" uuid not null
);


alter table "public"."temporary_account_profiles" enable row level security;

CREATE UNIQUE INDEX temporary_account_profiles_pkey ON public.temporary_account_profiles USING btree (id);

alter table "public"."temporary_account_profiles" add constraint "temporary_account_profiles_pkey" PRIMARY KEY using index "temporary_account_profiles_pkey";

alter table "public"."temporary_account_profiles" add constraint "temporary_account_profiles_one_time_code_id_fkey" FOREIGN KEY (one_time_code_id) REFERENCES one_time_codes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."temporary_account_profiles" validate constraint "temporary_account_profiles_one_time_code_id_fkey";

alter table "public"."temporary_account_profiles" add constraint "temporary_account_profiles_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."temporary_account_profiles" validate constraint "temporary_account_profiles_profile_id_fkey";


