name: Sync branches

on:
  push:
    branches:
      - chat-everywhere

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Sync branches
        run: |
          git checkout preview-production-cypress
          git merge origin/chat-everywhere
          git push origin preview-production-cypress
