name: Cypress tests

on:
  pull_request:
    types: [closed, synchronize, opened, edited]

jobs:
  start_cypress_tests:
    name: Start Cypress tests
    runs-on: ubuntu-latest
    steps:
      - run: sleep 210
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: "prj_RPBj6sI3IAMH9Wts1aUQ2PYn1u67"
          vercel_team_id: "team_r4LW8hqch5erbYdDR57PILPp"
      - name: Get URL
        run: echo "https://${{ steps.vercel_preview_url.outputs.preview_url }}"
