name: Cypress tests

on:
  pull_request:
    types: [closed, synchronize, opened, edited]

jobs:
  start_cypress_tests:
    name: Start Cypress tests
    runs-on: ubuntu-latest
    steps:
      # - run: sleep 180 # Wait for the Vercel preview to be ready
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: "prj_RPBj6sI3IAMH9Wts1aUQ2PYn1u67"
          vercel_team_id: "team_r4LW8hqch5erbYdDR57PILPp"

      - name: Print out the preview URL
        run: echo "https://${{ steps.vercel_preview_url.outputs.preview_url }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create cypress folders
        run: mkdir -p cypress/screenshots cypress/videos

      - name: Install pnpm
        run: npm install -g pnpm@9

      - name: Install packages and run Cypress tests
        uses: cypress-io/github-action@v6
        timeout-minutes: 30 # Limit Cypress tests run time to 30 minutes
        with:
          start: npm run cypress:run
          browser: chrome
        env:
          CYPRESS_HOST_URL: "https://${{ steps.vercel_preview_url.outputs.preview_url }}"

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
